export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_TOKEN = "SET_TOKEN"
export const SET_STATUS = "SET_STATUS"
export const LOGIN_USER = "LOGIN_USER"

export const GET_USERNAME = "GET_USERNAME"
export const GET_PASSWORD = "GET_PASSWORD"
export const GET_TOKEN = "GET_TOKEN"

export const FETCH_SUCCESSFUL = "FETCH_SUCCESSFUL";
export const FETCH_FAILED = "FETCH_FAILED";

export const POST_SUCCESSFUL = "POST_SUCCESSFUL";
export const POST_FAILED = "POST_FAILED";

export const VALIDATION_FAILED = "VALIDATION_FAILED";

